### ISSUE TITLE
vk_mem_alloc.h No such file or directory

### ISSUE THREAD

**Issue by hzbian** [hz-b/RAY-X#102]
When I compile now (as of 05a5d6a0ffd13e35010060d3937bdefc3268bb53), i get the following error:

> RAY-X/Intern/RayCore/src/VulkanEngine/VulkanEngine.h:3:10: schwerwiegender Fehler: vk_mem_alloc.h: Datei oder Verzeichnis 
> nicht gefunden
>     3 | #include <vk_mem_alloc.h>
>       |          ^~~~~~~~~~~~~~~~
> Kompilierung beendet.
> [37/69] Building CXX object Intern/RayCore/CMakeFiles/RayCore.dir/src/Tracer/CpuTracer.cpp.o
> ninja: build stopped: subcommand failed.
>

It happens both on release and debug.

**Comment by OSMaxwell** [comment]
Yes, I should write that soon in the docs. You need at least Vulkan 1.3 for the new addition as of 5fb016c47f0919244bb5487022f6bcd30c777ce9. 
Find it here : 
https://vulkan.lunarg.com/sdk/home#linux

Remove your old vulkan-sdk first before upgrading.
Overwriting vulkan-sdk can break stuff..

**Comment by Atraxus** [comment]
I have the same issue and I use Vulkan version 1.3.224.1.
So, it seems to be something different than the version...

**Comment by OSMaxwell** [comment]
Can it be Windows related? on the CI "Docker" machine it seems to be found...?

**Comment by hzbian** [comment]
Nope does also not work on the docker version. Furthermore, I use Vulkan 1.3 on my desktop now, I still have the same issue.

**Comment by Atraxus** [comment]
We talked about the issue in the meeting today. It seems not all Vulkan installations bring the vma headers, even if using v1.3+
@memoryleak47 reported, that there is an extra package on arch that he installed to make it work

**Comment by hzbian** [comment]
Is there the possibility to directly include this directly in our build repo?

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator

**Comment by OSMaxwell** [comment]
We did that on a different branch but now that the sdk offers that so we want to get away from that. Please try now :)
____
- If you are linking vulkan-sdk through shell with VULKAN-SDK, This should be working out of the box.

- If you are on **Ubuntu** or similar debian-based, please install **vma** (Something similar is also on arch)

- If you are on **WIndows**,  on the vulkan-sdk installation, check the **"Vulkan Memory Allocator header"** option

**Comment by Atraxus** [comment]
This should be fixed by 60007e4, where vma is included as a submodule

**Comment by hzbian** [comment]
This is fixed now. Is it merged to development yet?

**Comment by Atraxus** [comment]
Yes, this is on the dev branch.
