### ISSUE TITLE
Fix profiler trouble

### ISSUE THREAD

**Issue by memoryleak47** [hz-b/RAY-X#106]
Remove new Bench.* profiler.

The command line option for benchmarks should make the Instrumentor print a selected amount of durations to stdout.
Like vkDestroyDevice, vkCreateComputePipeline, trace etc.

**Comment by Atraxus** [comment]
We would like to have two ways of checking the timings: json & chromium trace, stdout. 
We could have the json file as standard behaviour and the -b flag adds timings to the stdout.

**Comment by Atraxus** [comment]
Instrumentor is now used to print out timers for -b mode. There is still some memory weirdness that timers inherit flag from timer from higher scope

**Comment by Atraxus** [comment]
It seems the problem fixed itself

**Comment by Atraxus** [comment]
- [ ] overall time for -b
- [ ] fix json file

**Comment by Atraxus** [comment]
Now it's done.
