### ISSUE TITLE
RZP bug

### ISSUE THREAD

**Issue by Atraxus** [hz-b/RAY-X#111]

**Comment by Atraxus** [comment]
![198572683-136e0f3d-a87b-4d78-b582-2f7a75a0dedb](https://user-images.githubusercontent.com/13185253/198576004-1b405e22-13fa-4959-a90f-1278f19b8c3f.png)
Issues marked blue

**Comment by treegardel** [comment]
Blue framed plots: Here z should be plotted over x because it is a reflective element.
This applies to all reflective optics:
- All mirrors and gratings
For transmissive optics, y should be plotted over x, i.e. Image Plane, Slit, etc.

**Comment by Atraxus** [comment]
Blue arrows might be fixed by recent commit

**Comment by Atraxus** [comment]
Light rays being reflected from one RZP to another doesn't seem to be an issue anymore.

**Comment by Atraxus** [comment]
Blue arrow plots reappeared with recent commits. I'm going to check this out

**Comment by Atraxus** [comment]
Fixed by the new plotting system
