### ISSUE TITLE
missing matplotlib

### ISSUE THREAD

**Issue by treegardel** [hz-b/RAY-X#116]
When using the commandline option -p I got the following error:

`[             Plotter.cpp:18] Plotting...
ModuleNotFoundError: No module named 'matplotlib'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error loading module matplotlib!
Aborted (core dumped)`

There must be something wrong with my Python Matplotlib, right?

**Comment by Atraxus** [comment]
Are you sure you installed the matplotlib Module?
(maybe try `python3 -m pip install matplotlib` to be sure)

**Comment by treegardel** [comment]
Thanks @Atraxus; with your command for installing the lib it works now.

**Comment by treegardel** [comment]
Strange - now it fails again with another error:
`Starting RAY-X (b74497dd, release)
Tracing File: "../../../../SimpleTest/MultiRun/METRIX_U41_G1_H1_318eV_PS_MLearn_AutoDIA_org1.rml"
[             Plotter.cpp:18] Plotting...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Call to title() failed.
Aborted (core dumped)`
(matplotlib is installed via pip)

**Comment by OSMaxwell** [comment]
Plot results might be still broken. But it should work now..?

**Comment by treegardel** [comment]
Command line option "-p -m" still not working...

`Starting RAY-X (0d5187d2, release)
Tracing File: "../../../../SimpleTest/MultiRun/METRIX_U41_G1_H1_318eV_PS_MLearn_AutoDIA_org1.rml"

[             Plotter.cpp:31] Plotting...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Call to subplot() failed.
Aborted (core dumped)`

**Comment by OSMaxwell** [comment]
matplotlib-cpp works so far with matplotlib==3.1.2
Installing through pip gives a more recent version.

Solved through matplotlib downgrade

**Comment by Atraxus** [comment]
I pushed a fix for this issue. For me, multi-plotting works now even with Python v3.10.
