### ISSUE TITLE
multiplot error:

### ISSUE THREAD

**Issue by treegardel** [hz-b/RAY-X#117]
When using the commandline options -p -m for getting the multiplot output, I get the following error:
`[             Plotter.cpp:18] Plotting...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Call to subplot() failed.
Aborted (core dumped)`
Should this already work in the "development" branch?

**Comment by OSMaxwell** [comment]
Can you please provide us the RML File that you're using. This is a matplotlibcpp error that shouldn't happen...

**Comment by OSMaxwell** [comment]
Closing, issue related to #116

**Comment by treegardel** [comment]
I still have the same error. I would say #116 can be closed because this issue I don't have anymore.

**Comment by treegardel** [comment]
Ok, lets continue this issue within issue #116
