### ISSUE TITLE
Compare Plotting Libraries

### ISSUE THREAD

**Issue by Atraxus** [hz-b/RAY-X#119]

**Comment by Atraxus** [comment]
Look at mathGL, plot utils and GNU plot
- also look for other SVG generating plotting libraries (perfect would be header-only)
- first priority: svg
- if that's not usable, look at GNU plot
- Plots don't need to look like RAY-UI (non-sequential tracing is a new feature, that should look different)

**Comment by OSMaxwell** [comment]
MathGL is now operating under mathgl branch
