### ISSUE TITLE
Multiplot: Simple Test to overilluminated mirrors, missing plots

### ISSUE THREAD

**Issue by treegardel** [hz-b/RAY-X#121]
Setup:
![image](https://user-images.githubusercontent.com/103497430/202434355-2db48371-cf65-41c9-a1c5-e700a26e4030.png)
RML-File:
[Simple2Plane_overIlluminated.zip](https://github.com/hz-b/RAY-X/files/10030985/Simple2Plane_overIlluminated.zip)
Result in RAY-X:
![image](https://user-images.githubusercontent.com/103497430/202434660-70d3f6e4-e49f-4760-9052-ecf2a3bdafad.png)

Plot for the source (Point Source, element 0), and the second mirror (PlaneMirror1, element 2) is missing

**Comment by treegardel** [comment]
Another example:
![image](https://user-images.githubusercontent.com/103497430/202440261-ec396d29-3565-4387-b24f-623b208ccb22.png)
RML-File: 
[DynamicMatrix-PM-IP.rml.txt](https://github.com/hz-b/RAY-X/files/10031229/DynamicMatrix-PM-IP.rml.txt)
![image](https://user-images.githubusercontent.com/103497430/202440446-885ec82a-80b8-42df-90f1-be991234fa5f.png)
Here I miss a plot the plane mirror (1 element) and also of the source.

**Comment by OSMaxwell** [comment]
Hi,
I don't think Source plotting is covered.
I will investigate the missing plane mirror problem
