### ISSUE TITLE
METRIX Beamline: multiplot gives 3 additional plots on last element which are not explainable

### ISSUE THREAD

**Issue by treegardel** [hz-b/RAY-X#128]
Running the METRIX Beamline: 
[METRIX_U41_G1_H1_318eV_PS_MLearn_MG.zip](https://github.com/hz-b/RAY-X/files/10359010/METRIX_U41_G1_H1_318eV_PS_MLearn_MG.zip)
and looking at the multiplot result:
![Multiplot](https://user-images.githubusercontent.com/103497430/210971180-6185fde5-2f30-41f4-a50e-1cc7a8f36fcc.png)
Shows 4 Plots, **but only the last plot "987654321" should appear**. The others are not explainable where they should come from.

![image](https://user-images.githubusercontent.com/103497430/210972329-b817f0db-caf0-4a03-9220-a512a10f74e5.png)

RAY-UI clearly shows that only at the first element (ASBL, slit) rays are "lost" due to absorption. After that, all rays pass sequentially over the other elements. So that only plot 987654321 is correct, these are the only rays that reach the last element (ImagePlane).

Plot "98765432": It looks like the rays absorbed at the slit are traced further with the status of being a new source.

**Comment by OSMaxwell** [comment]
Is the split too small compared to the Cylinder maybe? 2 is Cylinder which means 98765432 start from cylinder and ignore slit

**Comment by treegardel** [comment]
For me, 98765432 are exactly the rays that do not go through the aperture but are absorbed by the apertures, hence the white area in the middle. So they should not be traced further. The rays that pass through are correctly represented in 987654321.
Is it not possible to debug this relatively easily in -x mode?
It would also be interesting to see whether we still get 98765432 if we set the aperture so small that no rays come through at all. I'll try it out tomorrow.

Translated with www.DeepL.com/Translator (free version)

**Comment by treegardel** [comment]
Here is the result: I closed the front end aperture totally (by setting the slit size to zero/zero). All rays should be blocked, as in RAY-UI, but we still get the following plots:
![Figure_ClosedAperture](https://user-images.githubusercontent.com/103497430/213654186-99f8ffe2-5fa4-454f-a91e-3fffb2db5a06.png)
There must be a bug.

**Comment by Atraxus** [comment]
We changed our plotting
