### ISSUE TITLE
only 131072 Rays as max are traced

### ISSUE THREAD

**Issue by OSMaxwell** [hz-b/RAY-X#29]
```
[     TracerInterface.cpp:77] (*outputRayIterator).size(): 131072
[     TracerInterface.cpp:86] sample ray: -2218.48, 26406.1, -49981.7, 1, 0.1974, -0.953458, -0.227928, energy: 318, stokes 0: 1
[     TracerInterface.cpp:77] (*outputRayIterator).size(): 131072
[     TracerInterface.cpp:86] sample ray: 0, 0, 0, 0, 0, 0, 0, energy: 0, stokes 0: 0
[     TracerInterface.cpp:77] (*outputRayIterator).size(): 131072
[     TracerInterface.cpp:86] sample ray: 0, 0, 0, 0, 0, 0, 0, energy: 0, stokes 0: 0
[     TracerInterface.cpp:77] (*outputRayIterator).size(): 131072
[     TracerInterface.cpp:86] sample ray: 0, 0, 0, 0, 0, 0, 0, energy: 0, stokes 0: 0

```

The Tracer seems to ignore the tracing or there is something wrong with the copying handshake once VulkanTracer is done.

Note: 
```
[    TracerInterface.cpp:102] @86174
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:61] 
[    TracerInterface.cpp:102] @86175
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:61] 
[    TracerInterface.cpp:102] @86176
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:61] 
[    TracerInterface.cpp:102] @86177
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:56]   0, 0, 0, 0, 
[               utils.cpp:61] 
```

Debug Buffer is also empty which might show that the shader code is not called for every ray. Since the shader automatically sets the debugBuffer to the Identity matrix.

**Comment by treegardel** [comment]
With the attached simple test (with 9 mill rays) I get the following error:

[       VulkanTracer.cpp:764] Debug Info: more than 128MB of rays!
[       VulkanTracer.cpp:794] Vectors per StagingBuffer: 5
[       VulkanTracer.cpp:803] Debug Info: value: -0.0470407
[       VulkanTracer.cpp:805] Vector in StagingBuffer insterted! [RayList→StagingBuffer]
[       VulkanTracer.cpp:829] Copying [StagingBuffer→RayBuffer]: offset: 1073741824 size: 78258176 Bytes
[       VulkanTracer.cpp:845] Done.
[       VulkanTracer.cpp:774] Done.
[       VulkanTracer.cpp:249] RayBuffer filled, run time: 110.786 ms
[      VulkanTracer.cpp:1035] Filling QuadricBuffer..
[      VulkanTracer.cpp:1041] Done!
[      VulkanTracer.cpp:1046] Filling MaterialBuffer.. (size = 1 doubles)
[      VulkanTracer.cpp:1069] Done!
[       VulkanTracer.cpp:254] All buffers filled.
[      VulkanTracer.cpp:1240] Creating compute shader module..
[      VulkanTracer.cpp:1244] Shader module(s) created.
[      VulkanTracer.cpp:1247] Creating pipeline...
[      VulkanTracer.cpp:1282] Pipeline created.
[      VulkanTracer.cpp:1306] Creating commandBuffer..
[      VulkanTracer.cpp:1412] Dispatching commandBuffer...
[      VulkanTracer.cpp:1454] Fatal : VkResult fail!
[      VulkanTracer.cpp:1454] Error code: -4, look up at https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkResult.html
[      VulkanTracer.cpp:1454] Terminating...

[Slit_x450.zip](https://github.com/hz-b/RAY-X/files/9003098/Slit_x450.zip)

**Comment by treegardel** [comment]
I have deleted everything in the build folder and rebuild the TerminalApp: Now already the import does not work: (development brunch):
`baumgaertel@notexray04:~/RAY/RAY-X/build/bin$ ./TerminalApp -i ../../Tests/rml_files/test_shader/Ellipsoid.rml 
[           Importer.cpp:122] importBeamline is called with file ""../../Tests/rml_files/test_shader/Ellipsoid.rml""
[           Importer.cpp:129] importBeamline could not open file! (or it was just empty)
[           Importer.cpp:129] Terminating...`
