### ISSUE TITLE
simplify VulkanTracer (possible because of simpler API)

### ISSUE THREAD

**Issue by memoryleak47** [hz-b/RAY-X#51]
As the API surface of VulkanTracer was drastically reduced to just a single trace function.
It's implementation details can be re-ordered fearlessly now.

**Comment by OSMaxwell** [comment]
Cool Feature of the hpp version:

> UniqueHandle for automatic resource management
> 
> Vulkan-Hpp provides a vk::UniqueHandle<Type, Deleter> interface. For each Vulkan handle type vk::Type there is a unique handle vk::UniqueType which will delete the underlying Vulkan resource upon destruction, e.g. vk::UniqueBuffer is the unique handle for vk::Buffer.
> 
> For each function which constructs a Vulkan handle of type vk::Type Vulkan-Hpp provides a second version which returns a vk::UniqueType. E.g. for vk::Device::createBuffer there is vk::Device::createBufferUnique and for vk::allocateCommandBuffers there is vk::allocateCommandBuffersUnique.
> 
> Note that using vk::UniqueHandle comes at a cost since most deleters have to store the vk::AllocationCallbacks and parent handle used for construction because they are required for automatic destruction.
> Custom allocators

**Comment by memoryleak47** [comment]
This is done now.
Due to the VulkanEngine the VulkanTracer went from ~1500 LOC to 78 LOC.
