### ISSUE TITLE
Merge windows-build into dev

### ISSUE THREAD

**Issue by Atraxus** [hz-b/RAY-X#53]

**Comment by OSMaxwell** [comment]
Update: 
Please look at branch 'test' for a thorough example. 
The shader seems to stay stuck at the SquareRNG when running on CPU.

**Comment by memoryleak47** [comment]
wasn't it sometimes stuck at the `while (c < 0)` loop in `fraun_diff`?

**Comment by OSMaxwell** [comment]
Done. 01f8f4ff5737a6d230bb9981d3be5e037f247640
Tests also pass now.
