### ISSUE TITLE
Our simple Toroid test fails

### ISSUE THREAD

**Issue by treegardel** [hz-b/RAY-X#62]
Test https://github.com/hz-b/RAY-X/blob/master/Tests/rml_files/test_shader/toroid.rml fails:

At the image plane we should see the following foodprint:
![image](https://user-images.githubusercontent.com/103497430/176242765-a957324d-8dfb-4beb-9f55-685f420cb247.png)

But we see (right side):
![Image_Plane_Footprint_toroid](https://user-images.githubusercontent.com/103497430/176242851-90e2d3fa-9f7c-46af-9f71-c6a95308014d.png)

**Comment by treegardel** [comment]
@OSMaxwell
I was able to get the debugger running with your help and with the debugger I could fix the bug:
![Image_Plane_Footprint-toroid](https://user-images.githubusercontent.com/103497430/177184580-f58c7dcd-b967-4716-b224-a20b47c844fc.png)

So that we can turn on the test again.

**Comment by memoryleak47** [comment]
Currently, on development, Ray X and Ray UI yield different rays for this test. So to me it doesn't seem fixed yet.
Maybe something not yet merged?

**Comment by OSMaxwell** [comment]
Yes it's still seems wrong in the scaling Y and X intervals..
![image](https://user-images.githubusercontent.com/48519746/184360119-a0a1ddea-66a0-488c-987e-eebb8208fc6a.png)

**Comment by memoryleak47** [comment]
![image](https://user-images.githubusercontent.com/5725430/185787568-e297a619-10f4-4256-9be8-3d1604fdb7bb.png)
For me it looks like this.

**Comment by memoryleak47** [comment]
Yes, good observation!
The lowest y position is > -0.12 for RAYX and < -0.14 in RAY-UI.
The reason for this seems to be that a few rays in RAY-X miss the toroid.

As one can see in https://github.com/hz-b/RAY-X/issues/62#issuecomment-1173943272 above.

**Comment by memoryleak47** [comment]
It seems to be a wasteBox-bug of the toroid.
the wasteBox excludes too many rays.

If I return 1.0 in wasteBox all the time the test actually passes.

**Comment by memoryleak47** [comment]
Lustig, das Problem war, dass die Argumente zLength und xLength vertauscht waren in wasteBox, und das widerum lag daran, dass createFromXML die width und length falschrum in den Konstruktor gepackt hat.

Wieder etwas, was mit named-arguments anstelle von unzähligen unnamed args in constructors nicht passiert wäre.
