### ISSUE TITLE
change shader DEBUG macro with RAYX_DEBUG_MODE

### ISSUE THREAD

**Issue by memoryleak47** [hz-b/RAY-X#63]

**Comment by Atraxus** [comment]
As far as I can tell, this isn't easily doable since CMake compile definitions are for the c++ compiler and not for GLSLC. I think we could find a nicer way to do add the macro for GLSLC, but for now, I don't see a way how to unify this.

**Comment by memoryleak47** [comment]
we could add a -D option to the glslc call.

**Comment by OSMaxwell** [comment]
Cmake generates the settings.comp, there you can find RAYX_DEBUG_MODE instead of DEBUG now.

**Comment by OSMaxwell** [comment]
Seems to be solved 3fdb848d83a763fc3798f7999d0cbca2673d701d
Settings.comp is also deleted
