### ISSUE TITLE
Division by Zero in CPU Tracer

### ISSUE THREAD

**Issue by Atraxus** [hz-b/RAY-X#65]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/13185253/177516379-6f50a70f-5c0c-4ab7-886e-73b8f1a1cecb.png">

An often used expression in shader language to get infinity, is a problem when building with msvc ("division by zero" error)

**Comment by memoryleak47** [comment]
Fixed. This throws RAYX_ERR instead of 0/0 now.

**Comment by Atraxus** [comment]
This appears multiple times in the shader code.

**Comment by memoryleak47** [comment]
The problem is https://stackoverflow.com/questions/10435253/glsl-infinity-constant
So we need something else than 1/0.

**Comment by memoryleak47** [comment]
I solved this by using a large constant instead of infinity a few weeks ago.
