### ISSUE TITLE
Errors in Wiki

### ISSUE THREAD

**Issue by hzbian** [hz-b/RAY-X#92]
Add this to the required packages for Fedora:
`ninja-build gcc-c++ vulkan-loader-devel glslc`

And the order of the setup and compiliation commands building without IDE is wrong way round.

**Comment by memoryleak47** [comment]
Thanks! I added the fedora packages.
Additionally I added a `compile.sh` for a better non-IDE experience.
It's `compile.sh --release` for the release mode accordingly.

**Comment by hzbian** [comment]
Shouldn't it be the other way round?  A flag for debug and release otherwise?

**Comment by memoryleak47** [comment]
> Nice! But shouldn't it be the other way round? A flag for debug and release otherwise?

I did it like Rusts cargo. But I don't really mind.
If you want to, I can change --release to be the default.
