### ISSUE TITLE
h5 no such file or directory on -p

### ISSUE THREAD

**Issue by hzbian** [hz-b/RAY-X#93]
The ` -p`  option turns to the following error in Linux:

> Traceback (most recent call last):
>   File "/home/hzbian/RAY-X/build/bin/python/py_plot.py", line 160, in <module>
>     plotOutput(str(sys.argv[1]), int(sys.argv[2]))
>   File "/home/hzbian/RAY-X/build/bin/python/py_plot.py", line 146, in plotOutput
>     df = importOutput(h5_file)
>   File "/home/hzbian/RAY-X/build/bin/python/py_plot.py", line 23, in importOutput
>     with h5py.File(filename, 'r') as h5f:
>   File "/home/hzbian/RAY-X/build/bin/rayxvenv/lib64/python3.10/site-packages/h5py/_hl/files.py", line 533, in __init__
>     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
>   File "/home/hzbian/RAY-X/build/bin/rayxvenv/lib64/python3.10/site-packages/h5py/_hl/files.py", line 226, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 106, in h5py.h5f.open
> FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'METRIX_U41_G1_H1_318eV_PS_MLearn.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
> Traceback (most recent call last):
>   File "/home/hzbian/RAY-X/build/bin/python/py_plot_entry.py", line 24, in startPlot
>     output = subprocess.check_call(
>   File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/home/hzbian/RAY-X/build/bin/rayxvenv/bin/python3', '/home/hzbian/RAY-X/build/bin/python/py_plot.py', 'METRIX_U41_G1_H1_318eV_PS_MLearn.rml', '1']' returned non-zero exit status 1.
> [        TerminalApp.cpp:129] Error while running the python module: [ERR011]startPlot
> [        TerminalApp.cpp:129] Terminating...

**Comment by memoryleak47** [comment]
Hey,

on which commit are you? please try the newest version.
what command did you execute?

**Comment by hzbian** [comment]
Same problem on 368fde220a040ce7e7827e3c56e7c1c578336494.

**Comment by memoryleak47** [comment]
Ah, it's an absolute path problem.
I'll look into it.

Until it's fixed you can copy BL_file.rml to your TerminalApp and do
`./TerminalApp -x -i BL_file.rml -p` instead.

**Comment by memoryleak47** [comment]
Should be fixed now, please try again @hzbian

**Comment by hzbian** [comment]
This works now. Shouldn't this issue be covered by a unit test?

**Comment by memoryleak47** [comment]
Also, this error might just resolve itself once we plot within c++,
which is currently being implemented by Oussama.

So I'd say we'll wait a few weeks, and then re-check whether the issue remains.

**Comment by OSMaxwell** [comment]
Hello there, 
An almost similar plot version is now live on dev branch all written in C++ . (Though it still calls py interpreter internally.)

Make sure that you have python3, python3-dev and python3-matplotlib (also through pip) installed for this.

**Comment by hzbian** [comment]
This works now, no issue left. Thank you @OSMaxwell @memoryleak47 for the great work!
